name: hping3 Server Test

on:
  workflow_dispatch:

jobs:
  hping-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install hping3
        run: sudo apt-get install -y hping3

      - name: TCP SYN test (port 19132)
        run: sudo hping3 -S -p 19132 --flood mc.frostsmp.net
