name: hping3 Server Test

on:
  workflow_dispatch:

jobs:
  hping-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install hping3
        run: sudo apt-get install -y hping3

      - name: TCP SYN test (port 25565)
        run: sudo hping3 -S -p 25565 --flood play.voidsmp.space
